export const serviceWords = [
  { idToTable: 1, value: "program" },
  { idToTable: 2, value: "var" },
  { idToTable: 3, value: "begin" },
  { idToTable: 4, value: "as" },
  { idToTable: 5, value: "plus" },
  { idToTable: 6, value: "min" },
  { idToTable: 7, value: "mult" },
  { idToTable: 8, value: "div" },
  { idToTable: 9, value: "or" },
  { idToTable: 10, value: "and" },
  { idToTable: 11, value: "ne" },
  { idToTable: 12, value: "eq" },
  { idToTable: 13, value: "lt" },
  { idToTable: 14, value: "le" },
  { idToTable: 15, value: "gt" },
  { idToTable: 16, value: "ge" },
  { idToTable: 17, value: "end." },
  { idToTable: 18, value: "int" },
  { idToTable: 19, value: "float" },
  { idToTable: 20, value: "bool" },
  { idToTable: 21, value: "read" },
  { idToTable: 22, value: "write" },
  { idToTable: 23, value: "if" },
  { idToTable: 24, value: "then" },
  { idToTable: 25, value: "else" },
  { idToTable: 26, value: "while" },
  { idToTable: 27, value: "do" },
  { idToTable: 28, value: "for" },
  { idToTable: 29, value: "to" },
  { idToTable: 30, value: "true" },
  { idToTable: 31, value: "false" },
  { idToTable: 32, value: "AS" },
  { idToTable: 33, value: "PLUS" },
  { idToTable: 34, value: "MIN" },
  { idToTable: 35, value: "MULT" },
  { idToTable: 36, value: "DIV" },
  { idToTable: 37, value: "OR" },
  { idToTable: 38, value: "AND" },
  { idToTable: 39, value: "NE" },
  { idToTable: 40, value: "EQ" },
  { idToTable: 41, value: "LT" },
  { idToTable: 42, value: "LE" },
  { idToTable: 43, value: "GT" },
  { idToTable: 44, value: "GE" },
];

export const separators = [
  { idToTable: 1, value: "(" },
  { idToTable: 2, value: ")" },
  { idToTable: 3, value: "," },
  { idToTable: 4, value: ":" },
  // { idToTable: 5, value: "." },
  { idToTable: 5, value: ";" },
  { idToTable: 6, value: "[" },
  { idToTable: 7, value: "]" },
  { idToTable: 8, value: "\n" },
  { idToTable: 9, value: "}" },
  { idToTable: 10, value: "{" },
];

export const letters = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
];

export const figures = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"];
